### ISSUE TITLE
Daemon mode on myloader

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#1004]
@davidducos on a different note, can we have _daemon_ mode for **myloader** using the --daemon flag ? Currently it is not supported it seems, and ```nohup... &``` does not work because we need to enter password

_Originally posted by @madhurbhaiya in https://github.com/mydumper/mydumper/issues/993#issuecomment-1403084662_

**Comment by madhurbhaiya** [comment]
Hi,

Thanks for enlisting the feedback. But today I understood how the "daemon" mode works (after burning my hands) in the case of mydumper.

In case of mydumper, it seems to keep executing mydumper after a set time interval.

But in case of myloader, the only thing required would be to move the process to background, then execute once, and shut down at the end. It should not run in intervals.

Maybe, the flag should be --background instead of --daemon

**Comment by davidducos** [comment]
@madhurbhaiya that is something that you can do with screen or nohup.

**Comment by KDKSoftware** [comment]
@davidducos ```nohup``` might not work as it is required to enter password after running command, unless there is some other way to enter password in command line itself

screen / tmux are definitely the solution. Currently, I am using screen as well.

Just thought it would be nicer to have the same possibility with just a flag instead of doing these various terminal juggling

**Comment by davidducos** [comment]
@KDKSoftware you can use --defaults-file to set password for mydumper and myloader, or:
```
  -p, --password                   User password
```
which is obfuscated if you run ps.

**Comment by davidducos** [comment]
Taking into account the effort to implement this and that the execution of myloader will depend on several conditions, we are not going to implement it.
