### ISSUE TITLE
[BUG] myloader problem with restore to galera cluster

### ISSUE THREAD

**Issue by drMARTINS13** [mydumper/mydumper#1368]
I am trying to improve our method for database migration between clusters. 
My problem is that when i try same operation on same database i get two different result. 
once I managed to migrate the database but then with the same settings I got the following error again
`** (myloader:1341963): CRITICAL **: 15:00:01.373: Thread 3: Error restoring: Table 'databasename.tablename' doesn't exist`

I use mariadb galera cluster 10.6.16 with 3 nodes. Before nodes is haproxy
My mydumper and myloader usage looks like this

mydumper
`/usr/local/bin/mydumper -h $SOURCE_HOST -u user -p $(cat /user/.mysql_password) -B $DB_NAME -t 4 -o $BACKUP -c -v 3 -L /mnt/db_trashed/logs/$DB_NAME-backup.log`
myloader
`/usr/local/bin/myloader -h $TARGET_HOST -u user -p $(cat /user/.mysql_password) -B $DB_NAME -t 4 -o -d $BACKUP -v 3 --max-threads-for-schema-creation 1 --innodb-optimize-keys -L /mnt/db_trashed/logs/$DB_NAME-restore.log`

I build my own mydumper for mariadb 10.16
`mydumper v0.15.2-6, built against MariaDB 10.6.16 with SSL support`

before building my own i tried package v0.15.1-3 and v0.15.2-6 for Debian 11 (bullseye) but with these i have more trouble

it seems that the parameter `--max-threads-for-schema-creation 1` has no effect on the result. i got same error mentioned above

the same also applies to the parameter `--innodb-optimize-keys`

I'm not entirely sure that it's a bug, maybe I just have something wrong, but I don't know what it could be

**Comment by sw-ps** [comment]
@drMARTINS13 Do you run myloader against the haproxy instance? Then this is a bad idea.
Because each thread is opening its own connection to the database. In case of haproxy the end result is that not all connections are on the same real db node.
Due a design decision one threads starts importing data after the schema command was successfully executed for an table. (Which has other problems when using it against an galera cluster see my bugreport: #1358)
But in case of an galera cluster the create schema command might not have finished on the other nodes when the data import starts and the data import thread is connected to a different db node.
