### ISSUE TITLE
[FEATURE REQUEST] Support gtid replication and cloud based solutions

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#1572]
**Describe the Feature Request**
We should be able to configure replication using GTID using traditional replication or Galera.

**Current behavior**
Nowadays we have to execute action post restore to establish replication when GTID is used

**Expected behavior**
Be able to configure in the metadata file when backup is taken to let myloader knows that it must configure GTID. BTW, myloader needs to know if it is connected to a Galera based database and act properly.  

Reference :: https://docs.percona.com/percona-xtrabackup/8.0/create-gtid-replica.html#4-configure-and-start-replication

**Comment by reillski** [comment]
It would be handy if loader generated/executed the command to configure replication automatically too, similar to what mysqlshell/mysqldump does[1]. This could be controlled via a flag, and if possible custom formats could be used. e.g. [AWS](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/mysql-stored-proc-replicating.html)[2] and [Azure](https://learn.microsoft.com/en-us/azure/mysql/flexible-server/how-to-data-in-replication?tabs=bash%2Ccommand-line#link-source-and-replica-servers-to-start-data-in-replication) use stored procedures rather than "native" commands to configure replication so having a `--rds`/`--azure` flag for myloader or just a way for a user to pass a regex/format to the dump command, which auto parses metadata file for binlog coords would be nice. 

Thanks,
Marc

[1]
https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-shell-utilities-load-dump.html#mysql-shell-utilities-load-dump-opt-content see `showMetadata: [ true | false ]
` and `updateGtidSet: [ off | append | replace ]`
[2]
Example of RDS equivs:
CHANGE REPLICATION SOURCE
[mysql.rds_set_external_source](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/mysql-stored-proc-replicating.html#mysql_rds_set_external_source)
```
CALL mysql.rds_set_external_source (
  host_name
  , host_port
  , replication_user_name
  , replication_user_password
  , mysql_binary_log_file_name
  , mysql_binary_log_file_location
  , ssl_encryption
);
```
[GTID:](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/mysql-stored-proc-replicating.html#mysql_rds_set_external_master_with_auto_position)
```
CALL mysql.rds_set_external_source_with_auto_position (
  host_name
  , host_port
  , replication_user_name
  , replication_user_password
  , ssl_encryption
);
```
[mysql.rds_gtid_purged (Aurora MySQL version 3)](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/mysql-stored-proc-replicating.html#mysql_rds_gtid_purged)
```
CALL mysql.rds_gtid_purged (gtid_set);
OR
CALL mysql.rds_gtid_purged (+gtid_set);
```

**Comment by davidducos** [comment]
Hi @reillski, 
I liked this idea. Take into account that currently it is possible to instruct myloader to automatically connect using traditional replication. What I see from what you added, it is that we should be able to use store procedures in Azure/RDS to establish replication. 

Title updated!

**Comment by reillski** [comment]
Thanks David! If you get a chance to implement this, please feel free to give me a shout if you want me to do some sanity checks on RDS. 
Thanks!
Marc

**Comment by reillski** [comment]
Hi @davidducos 
Thanks for looking at this. I took it for a spin on the main branch and have a couple comments:
- For `exec_start_slave`/`start slave` rds also has a custom stored procedure - [call mysql.rds_start_replication()](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/mysql-stored-proc-replicating.html#mysql_rds_start_replication) rather than start slave
- For reset slave rds also has a custom stored procedure - [call mysql.reset_external_source()](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/mysql-stored-proc-replicating.html#mysql_rds_reset_external_source) / [call mysql.reset_external_master()](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/mysql-stored-proc-replicating.html#mysql_rds_reset_external_master)
- Also, thinking more about this: In aurora mysql version 3 stored procedures were added to use inclusive terminology in line with upstream MySQL where master was changed with source, i.e. `mysql.rds_set_external_source` rather than `mysql.rds_set_external_master` . However, other versions such as RDS MySQL 57/80 and Aurora MySQL version 2 do not support these procedures yet. I included a matrix below, but do you think it would be better to use older terminology(*master rather than *source procs) until all engines support the new "source" commands? The master commands work on all current releases, and inputs to the stored procs are identical, it's just the names which have changed.[1] The only other solution I can think of is to try detect the target version, but I think that may add too much complexity? You can see full info [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Compare-v2-v3.html#AuroraMySQL.8.0-inclusive-language). 

**Matrix:**
|          MySQL command          |                   RDS command                    | RDS MySQL 5.7 | RDS MySQL 8.0 | Aurora version 2 (5.7 Compat) | Aurora version 3 (8.0 Compat) |
|---------------------------------|--------------------------------------------------|---------------|---------------|-------------------------------|-------------------------------|
| CHANGE REPLICATION SOUCE        | mysql.rds_set_external_master                    | YES           | YES           | YES                           | YES (deprecated) (             |
| CHANGE REPLICATION SOUCE        | mysql.rds_set_external_source                    | NO            | NO            | NO                            | YES                           |
| CHANGE REPLICATION SOUCE (GTID) | mysql.rds_set_external_master_with_auto_position | YES           | YES           | YES                           | YES  (deprecated)*             |
| CHANGE REPLICATION SOUCE (GTID) | mysql.rds_set_external_source_with_auto_position | NO            | NO            | NO                            | YES                           |
| RESET REPLICA                   | mysql.rds_reset_external_master                  | YES           | YES           | YES                           | YES (deprecated)*              |
| RESET REPLICA                   | mysql.rds_reset_external_source                  | NO            | NO            | NO                            | YES                           |
| START REPLICA                   | mysql.rds_start_replication                      | YES           | YES           | YES                           | YES                           |
| STOP REPLICA                    | mysql.rds_stop_replication                       | YES           | YES           | YES                           | YES                           |

*Still works but will be removed in future


Couple other thing I noticed, can open a separate issue if you prefer: 
- Unrelated to RDS is that the mydumper metadata does not seem to contain `SOURCE_PORT`, unless I'm doing something wrong. While dumping from dbdeployer, which uses non-standard ports replication could not be configured due to myloader defaulting to 3306
- When dumping from localhost a socket file would be used. When this is done `source_host` in the mydumper metadata is null, so replication does not get configured correctly. Maybe this can also be provided from the mydumper command or retrieved from the os, not sure. e.g. metadata output
```
$ ~/mydumper/mydumper --user=msandbox --password=msandbox --socket=/tmp/mysql_sandbox8039.sock --port=8039 --outputdir=/home/ec2-user/sandboxes/dump_binlog/ --threads=10 --chunk-filesize=100 --verbose=3 --order-by-primary --csv --load-data --database=test --clear --source-data=1

$ head -n20  /home/ec2-user/sandboxes/dump_binlog/metadata
# Started dump at: 2024-07-31 03:43:09
.
.
[source]
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
#SOURCE_HOST = "(null)"
#SOURCE_USER = ""
#SOURCE_PASSWORD = ""
SOURCE_LOG_FILE = "binlog.000047"
SOURCE_LOG_POS = 6332142
executed_gtid_set = "00008039-0000-0000-0000-000000008039:1-16210738"
#SOURCE_SSL = {0|1}
#SOURCE_AUTO_POSITION = {0|1}
myloader_exec_reset_replica = 1
myloader_exec_change_source = 0
myloader_exec_start_replica = 0
```

Sorry for not being more thorough on the stored procedures naming/nuances first time round, please lmk if you need me to clarify anything. 

Thanks!
Marc


[1]
```
mysql> select @@version,@@aurora_version;
+-----------+------------------+
| @@version | @@aurora_version |
+-----------+------------------+
| 8.0.36    | 3.07.1           |
+-----------+------------------+
1 row in set (0.00 sec)

mysql> show create procedure mysql.rds_set_external_master\G
*************************** 1. row ***************************
           Procedure: rds_set_external_master
            sql_mode: NO_ENGINE_SUBSTITUTION
    Create Procedure: CREATE DEFINER=`rdsadmin`@`localhost` PROCEDURE `rds_set_external_master`(
    IN host VARCHAR(255),
    IN port INT,
    IN user TEXT,
    IN passwd TEXT,
    IN name TEXT,
    IN pos BIGINT UNSIGNED,
    IN enable_ssl_encryption BOOLEAN
)
    READS SQL DATA
    DETERMINISTIC
BEGIN
  SELECT 'rds_set_external_master is deprecated and will be removed in a future release. Use rds_set_external_source instead. Refer to the documentation for more information on deprecated statements' AS Message;
  CALL `mysql`.`rds_set_external_source`(host, port, user, passwd, name, pos, enable_ssl_encryption);
END
character_set_client: utf8mb4
collation_connection: utf8mb4_0900_ai_ci
  Database Collation: utf8mb4_0900_ai_ci
1 row in set (0.00 sec)
mysql> show create procedure mysql.rds_set_external_source\G
*************************** 1. row ***************************
           Procedure: rds_set_external_source
            sql_mode: NO_ENGINE_SUBSTITUTION
    Create Procedure: CREATE DEFINER=`rdsadmin`@`localhost` PROCEDURE `rds_set_external_source`(
    IN host VARCHAR(255),
    IN port INT,
    IN user TEXT,
    IN passwd TEXT,
    IN name TEXT,
    IN pos BIGINT UNSIGNED,
    IN enable_ssl_encryption BOOLEAN
)
.
.
.
character_set_client: utf8mb4
collation_connection: utf8mb4_0900_ai_ci
  Database Collation: utf8mb4_0900_ai_ci
1 row in set (0.00 sec)

mysql>
```

**Comment by davidducos** [comment]
Hi @reillski,
We are going to be using this store procedures:
- rds_set_external_master
- rds_set_external_master_with_auto_position
- rds_reset_external_master
- rds_start_replication

As they work on all the versions for now.
I added the SOURCE_PORT on the metadata file. 
Take into account that you can edit the metadata file and add any setting that you what to send on the change master. If you want to add a socket, you can do it. I kept in the metadata file the settings which I consider minimal and/or mandatory.

We could include all of them, we do when we extract the replication info, but I don't want to maintain if in the future some vendor decide to add or remove variables.

**Comment by reillski** [comment]
Perfect! Thanks, @davidducos !

**Comment by reillski** [comment]
Hey @davidducos 
I got this error, perhaps the two procedures can be split into separate commands similar to how native `change replication source` and `start slave` are?

```
$ myloader --user=username --password=password --host=rdshost.xxx-east-1.rds.amazonaws.com --database=test --directory=/home/ec2-user/sandboxes/dump_binlog/ --threads=20 --verbose=2 --source-control-command=aws --set-gtid-purged

** (myloader:211390): WARNING **: 17:51:37.465: Sending CHANGE MASTER: CALL mysql.rds_set_external_master_with_auto_position( "10.0.8.190", 8039, "user", "password", 0 );CALL mysql.rds_start_replication(); - ERROR 2014: Commands out of sync; you can't run this command now

```

Manually running the above works, so I assume its mutlstatement being disabled in myloader or deprecation warning returned from the first proc causes issues. 
```
mysql> CALL mysql.rds_set_external_master_with_auto_position( "10.0.8.190", 8039, "user", "password", 0 );CALL mysql.rds_start_replication();
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Message                                                                                                                                                                                                                            |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| rds_set_external_master_with_auto_position is deprecated and will be removed in a future release. Use rds_set_external_source_with_auto_position instead. Refer to the documentation for more information on deprecated statements |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.18 sec)

Query OK, 0 rows affected (0.18 sec)

+---------------------------+
| Message                   |
+---------------------------+
| Replica running normally. |
+---------------------------+
1 row in set (2.02 sec)

Query OK, 0 rows affected (2.02 sec)
```

Thanks,
Marc

**Comment by davidducos** [comment]
Seems that there is a missing '\n'

**Comment by davidducos** [comment]
https://github.com/mydumper/mydumper/commit/4b7910000bbbf6fa0096bdfc67be3f1fb0529d66
