### ISSUE TITLE
mysqlpump like skip-definer option

### ISSUE THREAD

**Issue by matthewlenz** [mydumper/mydumper#378]
mysqlpump supports skipping the definer on triggers and routines.  This would be really nice to have in mydumper when snapshotting a db to load up for development in a different environment.

**Comment by davidducos** [comment]
Hi @matthewlenz, I prefer to dump triggers and routines as it was created. During loading we can parse the CREATE statement and make some changes. We are already doing that on myloader when we have to parse the CREATE TABLE statement to remove the indexes to create the ALTER TABLE statement to add them later.

**Comment by matthewlenz** [comment]
@davidducos I was actually going to suggest that as an alternative in my original post.  I think your way is superior without a doubt.  Thanks for considering adding this and thanks for all the advancements in the project you've been spearheading!

**Comment by druud** [comment]
See also #84, nr 6.

**Comment by kamazee** [comment]
Is it closed because `--skip-definer` is implemented in `myloader`?
I think having `--skip-definer` in both `mydumper` and `myloader` has its benefits: `myloader` can load a wider variety of dumps this way but throwing the definer away from the dump upon creation makes the dump itself more portable: this way it can be loaded into any database using any tool.

If indeed it only exists in `myloader`, could you revisit the decision to not add it into `mydumper`?

**Comment by davidducos** [comment]
Hi @kamazee, 
Yes, it was closed because we (well it was actually just me) decided that it was simpler to implement it in myloader. 
I think that you have some good points in your argument. However, I'm wondering in which databases you will not be able to use myloader? Because MyDumper is for MySQL/Percona/MariaDB, it was not designed to work with other engines.
And, if I accept to implement in mydumper for portability with other database, then other user could ask for other changes. I open to hear any feature request, but they will need to be not just implemented, the will need to be maintain.

I based my decision on that ```I prefer to dump triggers and routines as it was created``` the only thing that we are changing is the data for data masking, we are not modifying DDL at dump stage and we are leaving the modifications on myloader. I still think that statement as valid, but I'm open to hear other opinions.
