### ISSUE TITLE
[ENHANCEMENT] hardlink snapshot backup aid: write file only if table was updated

### ISSUE THREAD

**Issue by klemens-u** [mydumper/mydumper#421]
For hardlink snapshot backups it would be great if mydumper could only write "per table dump files" if the data in the corresponding table has changed. Benefit: unchanged tables would not take up extra space in hardlink snapshot backups.

This would work as follows:

- mydumper gets a list of files and file modify dates in the given output directory
- mydumper checks the update time of each table. This can be done with:
``` 
SELECT UPDATE_TIME FROM information_schema.tables WHERE TABLE_SCHEMA = 'my_db' AND TABLE_NAME = 'my_table';
```
Note: if the update_time is NULL, dump only if the file does not exist.
- mydumper compares the dates
- mydumper dumps only into the output file if the table update date is greater than the file modify date. Otherwise it does nothing for this table to leave the file unchanged.

**Comment by davidducos** [comment]
Hi @klemens-u,
I think that you can do what you are requesting without implementing anything in mydumper, this is because:
1- you know when the backup has been taken
2- you can use a similar query: `SELECT concat(TABLE_SCHEMA,concat(".",TABLE_NAME)) FROM information_schema.tables WHERE UPDATE_TIME > @bkp_date;`
3- you can use -T with the output of 2- 

If what you want is incremental backup, we could implement that but we are going to do it using a configuration file that is going to be loaded, it is just an idea and there is no ticket yet to implement it as I think that it will be the best approach, we only have https://github.com/maxbube/mydumper/issues/148 that it is similar but lacks the full implementation.

So, just to confirm, do you want incremental backups?

**Comment by davidducos** [comment]
@klemens-u built in that query in mydumper is not a good idea from my point of view. Adding this custom queries inside mydumper will cause maintenance costs that I don't want to pay. We already implemented where options per table that might be even better! 
Please, check that and let me know, I will be closing this as wont fix for now.
