### ISSUE TITLE
Request to change versioning from X.X.X-X to X.X.X.X (by replacing dash with dot)

### ISSUE THREAD

**Issue by sunpoet** [mydumper/mydumper#688]
Is it OK to change versioning from X.X.X-X to X.X.X.X (by replacing dash with dot)?
FreeBSD Ports do not use dash in the version number.
Therefore, it would be better if you could use X.X.X.X instead.
Thanks.

**Comment by davidducos** [comment]
Hi @sunpoet ,
After the - (dash) is the number of the iteration of a release. Just the highest number must be used as any lower number has a bug that affects the usability of the software and must not be used. Actually, must be replaced ASAP. I leaving those releases, because I like to keep track of what has been released. 
So, for any OS, they should be packaging only the latest version of the minor/major release and anything after the - (dash) can/should/must be removed.
