### ISSUE TITLE
[BUG] WARNING It was not possible to process file: because real_db_name isn't found.

### ISSUE THREAD

**Issue by bmesich** [mydumper/mydumper#837]
**Describe the bug**
When attempting to restore a database, I am getting the following warning:
```
** (myloader:124446): WARNING **: 11:38:56.769: It was not possible to process file: sitemanager.tutorials_tbl-metadata (2) because real_db_name isn't found. We might renqueue it, take into account that restores without schema-create files are not supported
```
This is very similar to the issue [683](https://github.com/mydumper/mydumper/issues/683) and appears to have been fixed in [708](https://github.com/mydumper/mydumper/pull/708).  In this case, a WARNING is being generated rather than a CRITICAL log severity. 

**To Reproduce**
I used more-or-less the same steps to reproduce the warning as was shown in issue 683

MySQL Console
```
create database sitemanager;
use sitemanager;
create table tutorials_tbl(
tutorial_id INT NOT NULL AUTO_INCREMENT,
tutorial_title VARCHAR(100) NOT NULL,
tutorial_author VARCHAR(40) NOT NULL,
submission_date DATE,
PRIMARY KEY ( tutorial_id )
);
```

BASH Shell
```
mydumper --routines --triggers -S /var/lib/mysql/mysql.sock -o /backup-prep/sitemanager -B sitemanager
myloader -S /var/lib/mysql/mysql.sock -d /backup-prep/sitemanager
```
myloader generates the following WARNING:
```
** (myloader:124446): WARNING **: 11:38:56.769: It was not possible to process file: sitemanager.tutorials_tbl-metadata (2) because real_db_name isn't found. We might renqueue it, take into account that restores without schema-create files are not supported
```

**What mydumper and myloader version has been used?**
myloader 0.12.7-3, built against MySQL 10.6.9
mydumper 0.12.7-3, built against MySQL 10.6.9-MariaDB

**Expected behavior**
It would appear that the database is restored successfully if the WARNING log messages are ignored.  Perhaps this WARNING should be suppressed or prevented from appearing. 

**Log**
```
** Message: 12:02:07.520: Server version reported as: 10.6.9-MariaDB-log
** Message: 12:02:07.523: Intermediate queue ending

** (myloader:125010): WARNING **: 12:02:07.524: It was not possible to process file: sitemanager.tutorials_tbl-metadata (2) because real_db_name isn't found. We might renqueue it, take into account that restores without schema-create files are not supported
** Message: 12:02:07.524: Thread 1 restoring create database on `sitemanager` from sitemanager-schema-create.sql
** Message: 12:02:07.524: Intermediate thread ended
** Message: 12:02:07.524: Intermediate thread ended
** Message: 12:02:07.524: Thread 1: Data import ended
** Message: 12:02:07.524: Thread 3: Data import ended
** Message: 12:02:07.524: Thread 3: Starting post import task over table
** Message: 12:02:07.524: Thread 2 restoring table `sitemanager`.`tutorials_tbl` from //backup-prep/sitemanager/sitemanager.tutorials_tbl-schema.sql
** Message: 12:02:07.524: Thread 2: Creating table `sitemanager`.`tutorials_tbl` from content in //backup-prep/sitemanager/sitemanager.tutorials_tbl-schema.sql
** Message: 12:02:07.524: Thread 1: Starting post import task over table
** Message: 12:02:07.524: Thread 4: Data import ended
** Message: 12:02:07.524: Thread 4: Starting post import task over table
** Message: 12:02:07.530: Thread 2: Data import ended
** Message: 12:02:07.530: Thread 2: Starting post import task over table
** Message: 12:02:07.531: Starting table checksum verification
```

**Backup**
```
-rw-r--r-- 1 root root  75 Sep 23 11:33 metadata
-rw-r--r-- 1 root root  98 Sep 23 11:33 sitemanager-schema-create.sql
-rw-r--r-- 1 root root   1 Sep 23 11:33 sitemanager.tutorials_tbl-metadata
-rw-r--r-- 1 root root 377 Sep 23 11:33 sitemanager.tutorials_tbl-schema.sql
```
**How to repeat**
See steps above to repeat.  Note that using "-B ${DB_NAME}" argument to myloader will suppress the log WARNING.

**Environment (please complete the following information):**
 - OS version: RHEL9.0
 - MyDumper version: mydumper 0.12.7-3, built against MySQL 10.6.9-MariaDB

**Comment by davidducos** [comment]
I think that we don't print any message if a metadata file is processed, so we don't know if the file was processed but I think that we are successfully processing those files.
I'm agree that we can remove the Warning, we can move to debug and just print a warning or critical if a file was not processed because it reaches to the maximal amount of attempts which is 5.

**Comment by fenidik** [comment]
Have same issue. You should test with data. Because when I'm trying to restore it creates schema but not uploading the data.

mydumper --compress --defaults-file .my.cnf -t 10 # defaults file only contains db credentials
myloader --defaults-file ../.my.cnf -t 10 -d .

**Comment by davidducos** [comment]
@fenidik, we are testing with data. Can you give more details about your issue? MyDumper version used? Database version? a test case with CREATE TABLE and INSERT statements?

**Comment by bigkahuna1986** [comment]
Also have the same issue as @fenidik. `myloader` is producing a huge amount of warnings but not restoring any data.

`$ myloader --version`
`myloader 0.12.7-3, built against MySQL 8.0.29-21`

`Server version: 10.6.10-MariaDB-1:10.6.10+maria~ubu2004-log mariadb.org binary distribution`

My workflow is I restore our production database to my workstation from a mysqldump. We have about 100 databases most of which are less than 100mb (total size is around 15gb, biggest DB is just over 1gb). At this point I launch our application and run tests with no problems so I know the restore worked. Then I create a dump file using the following command:
`$ mydumper --defaults-file mydumper.conf  --regex 'my_dbs_prefix*' --outputdir /backups --compress`

It's worth noting Maria is in a docker container.

The dump seems to work well, with the `/backups` directory containing ~625mb of gzipped data.

mydumper.conf contains:
`[mydumper]`
`user = {redacted}`
`password = {redacted}`
`socket = /opt/mariadb/var/mysql.sock`

`[myloader]`
`user = {redacted}`
`password = {redacted}`
`socket = /opt/mariadb/var/mysql.sock`
`innodb-optimize-keys = AFTER_IMPORT_PER_TABLE`

Since this is production data I can't upload that as a test case. I'll try to find something smaller 

Load command:
`myloader --directory /backups --defaults-file mydumper.conf --queries-per-transaction 5000 --threads 8 --overwrite-tables`

At this point, `myloader` seems to create begin overwriting the first table but never does the work. For about 90 seconds Maria has moderate CPU usage (~30-50%), then goes completely idle. `myloader` is using 100% CPU, Maria is idle and can be restarted. I have to `kill -9` the process.

**Comment by davidducos** [comment]
Hi @bigkahuna1986,
Can you test latest prerelease (v0.13.0-6) and let me know if you see your issue with it?

**Comment by davidducos** [comment]
@vega-punk what version are you using?

**Comment by vega-punk** [comment]
> @vega-punk你用的是什么版本？

mydumper 0.12.3-3, built against MySQL 5.7.37-40
myloader 0.12.3-3, built against MySQL 5.7.37-40

centos7.6   3.10.0-693.el7.x86_64

**Comment by davidducos** [comment]
Please, test with the latest prerelease.
